### ISSUE TITLE
Does not work with react 16.0

### ISSUE THREAD

**Issue by pmnc** [mthuret/storybook-addon-specifications#77]
where would be the correct place to configure the react adapter for enzyme ?

Does not work either with latest version of storybook maybe for the same reason.

**Comment by nchery** [comment]
I've created a config file for enzyme that i'm importing into the setup file of jest

```
Jest.json
...
  "setupFiles": [
    "raf/polyfill",
    "<rootDir>/client/src/storybook/__conf__/jestMockConfig.js",
    "<rootDir>/client/src/storybook/__conf__/enzymeConf.js"
  ],
...
```

Prior this I was having the following error message while running unit tests

>  Enzyme Internal Error: Enzyme expects an adapter to be configured, but found none. To
>           configure an adapter, you should call `Enzyme.configure({ adapter: new Adapter() })`
>           before using any of Enzyme's top level APIs, where `Adapter` is the adapter
>           corresponding to the library currently being tested. For example:
> 

Adding the Enzyme adapter config resolved this particular issue but I still have a handful of other issues using storybook-addon-specifications with React v16 such as :

> Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

> TypeError: parentInstance.children.indexOf is not a function

> Enzyme Internal Error: unknown node with tag 4

Knowing that all these tests are passing on the previous config with React v15

**Comment by mthuret** [comment]
It needs to be tested and probably adapt for React 16.

I'll try to do it but I don't have that much time, so if someone wants to take this subject and submit a PR, it would be awesome!

**Comment by main-kun** [comment]
We were able to resolve this issue by adding `Enzyme.configure()` call inside storybook/config.js.
